In [2]:
import pandas as pd
import numpy as np
# Read data from a csv file and store as a dataframe.
cities = pd.read_csv('D:/KAUSHIK/kjn/workspace/Python/FILES/City_list_file.csv')

#change the index from default index to city name
cities.set_index('City', inplace=1)
cities.index.name = 'City'

#Sort the index based on alphabetical order (reverse = 1 for rev alph order.
cities = cities.reindex(sorted(cities.index, reverse=0))
print (cities)

#drop the column No from the Dframe.
cities.drop(['No'],axis=1,inplace=True)

print(cities)

                  No  Population_2011  Population_2001              State
City
Agra              23          1574542          1275134      Uttar Pradesh
Ahmedabad          5          5570585          3520085            Gujarat
Allahabad         36          1117094           975393      Uttar Pradesh
Amritsar          34          1132761           966862             Punjab
Anantnag          37          1078692           778408  Jammu and Kashmir
Aurangabad        32          1171330           873311        Maharashtra
Bangalore          3          8425970          4301326          Karnataka
Bhopal            17          1795648          1437354     Madhya Pradesh
Chandigarh        49           960787           808515         Chandigarh
Chennai            6          4681087          4343645         Tamil Nadu
Coimbatore        40          1061447           930882         Tamil Nadu
Delhi              2         11007835          9879172              Delhi
Dhanbad           33          1161561          1065327          Jharkhand
Faridabad         25          1404653          1055938            Haryana
Ghaziabad         21          1636068           968256      Uttar Pradesh
Guwahati          48           963429           809895              Assam
Gwalior           42          1053505           827026     Madhya Pradesh
Howrah            39          1072161          1007532        West Bengal
Hyderabad          4          7170545          3637483          Telangana
Indore            14          1960631          1474968     Madhya Pradesh
Jabalpur          41          1054336           932484     Madhya Pradesh
Jaipur            10          3073350          2322575          Rajasthan
Jodhpur           44          1033918           851051          Rajasthan
Kalyan-Dombivali  28          1246381          1193512        Maharashtra
Kanpur            12          2767031          2551337      Uttar Pradesh
Kolkata            7          4486679          4572876        West Bengal
Kota              47          1001365           694316          Rajasthan
Lucknow           11          2815601          2185927      Uttar Pradesh
Ludhiana          22          1613878          1398467             Punjab
Madurai           45          1016885           928869         Tamil Nadu
Meerut            26          1309023          1039405      Uttar Pradesh
Mumbai             1         12478447         11978450        Maharashtra
Nagpur            13          2405421          2052066        Maharashtra
Nashik            24          1486973          1077236        Maharashtra
Navi Mumbai       35          1119477           704002        Maharashtra
Patna             19          1683200          1366444              Bihar
Pimpri-Chinchwad  18          1729359          1012472        Maharashtra
Pune               9          3115431          2538473        Maharashtra
Raipur            46          1010087           605747       Chhattisgarh
Rajkot            27          1286995           967476            Gujarat
Ranchi            38          1073440           847093          Jharkhand
Solapur           50           951118           872478        Maharashtra
Srinagar          31          1192792           898440  Jammu and Kashmir
Surat              8          4462002          2433835            Gujarat
Thane             16          1818872          1262551        Maharashtra
Vadodara          20          1666703          1306227            Gujarat
Varanasi          30          1201815          1091918      Uttar Pradesh
Vasai-Virar       29          1221233           693350        Maharashtra
Vijayawada        43          1034358           851282     Andhra Pradesh
Visakhapatnam     15          1897823           982904     Andhra Pradesh
                  Population_2011  Population_2001              State
City
Agra                      1574542          1275134      Uttar Pradesh
Ahmedabad                 5570585          3520085            Gujarat
Allahabad                 1117094           975393      Uttar Pradesh
Amritsar                  1132761           966862             Punjab
Anantnag                  1078692           778408  Jammu and Kashmir
Aurangabad                1171330           873311        Maharashtra
Bangalore                 8425970          4301326          Karnataka
Bhopal                    1795648          1437354     Madhya Pradesh
Chandigarh                 960787           808515         Chandigarh
Chennai                   4681087          4343645         Tamil Nadu
Coimbatore                1061447           930882         Tamil Nadu
Delhi                    11007835          9879172              Delhi
Dhanbad                   1161561          1065327          Jharkhand
Faridabad                 1404653          1055938            Haryana
Ghaziabad                 1636068           968256      Uttar Pradesh
Guwahati                   963429           809895              Assam
Gwalior                   1053505           827026     Madhya Pradesh
Howrah                    1072161          1007532        West Bengal
Hyderabad                 7170545          3637483          Telangana
Indore                    1960631          1474968     Madhya Pradesh
Jabalpur                  1054336           932484     Madhya Pradesh
Jaipur                    3073350          2322575          Rajasthan
Jodhpur                   1033918           851051          Rajasthan
Kalyan-Dombivali          1246381          1193512        Maharashtra
Kanpur                    2767031          2551337      Uttar Pradesh
Kolkata                   4486679          4572876        West Bengal
Kota                      1001365           694316          Rajasthan
Lucknow                   2815601          2185927      Uttar Pradesh
Ludhiana                  1613878          1398467             Punjab
Madurai                   1016885           928869         Tamil Nadu
Meerut                    1309023          1039405      Uttar Pradesh
Mumbai                   12478447         11978450        Maharashtra
Nagpur                    2405421          2052066        Maharashtra
Nashik                    1486973          1077236        Maharashtra
Navi Mumbai               1119477           704002        Maharashtra
Patna                     1683200          1366444              Bihar
Pimpri-Chinchwad          1729359          1012472        Maharashtra
Pune                      3115431          2538473        Maharashtra
Raipur                    1010087           605747       Chhattisgarh
Rajkot                    1286995           967476            Gujarat
Ranchi                    1073440           847093          Jharkhand
Solapur                    951118           872478        Maharashtra
Srinagar                  1192792           898440  Jammu and Kashmir
Surat                     4462002          2433835            Gujarat
Thane                     1818872          1262551        Maharashtra
Vadodara                  1666703          1306227            Gujarat
Varanasi                  1201815          1091918      Uttar Pradesh
Vasai-Virar               1221233           693350        Maharashtra
Vijayawada                1034358           851282     Andhra Pradesh
Visakhapatnam             1897823           982904     Andhra Pradesh

In [9]:
cities['State']

City
Agra                    Uttar Pradesh
Ahmedabad                     Gujarat
Allahabad               Uttar Pradesh
Amritsar                       Punjab
Anantnag            Jammu and Kashmir
Aurangabad                Maharashtra
Bangalore                   Karnataka
Bhopal                 Madhya Pradesh
Chandigarh                 Chandigarh
Chennai                    Tamil Nadu
Coimbatore                 Tamil Nadu
Delhi                           Delhi
Dhanbad                     Jharkhand
Faridabad                     Haryana
Ghaziabad               Uttar Pradesh
Guwahati                        Assam
Gwalior                Madhya Pradesh
Howrah                    West Bengal
Hyderabad                   Telangana
Indore                 Madhya Pradesh
Jabalpur               Madhya Pradesh
Jaipur                      Rajasthan
Jodhpur                     Rajasthan
Kalyan-Dombivali          Maharashtra
Kanpur                  Uttar Pradesh
Kolkata                   West Bengal
Kota                        Rajasthan
Lucknow                 Uttar Pradesh
Ludhiana                       Punjab
Madurai                    Tamil Nadu
Meerut                  Uttar Pradesh
Mumbai                    Maharashtra
Nagpur                    Maharashtra
Nashik                    Maharashtra
Navi Mumbai               Maharashtra
Patna                           Bihar
Pimpri-Chinchwad          Maharashtra
Pune                      Maharashtra
Raipur                   Chhattisgarh
Rajkot                        Gujarat
Ranchi                      Jharkhand
Solapur                   Maharashtra
Srinagar            Jammu and Kashmir
Surat                         Gujarat
Thane                     Maharashtra
Vadodara                      Gujarat
Varanasi                Uttar Pradesh
Vasai-Virar               Maharashtra
Vijayawada             Andhra Pradesh
Visakhapatnam          Andhra Pradesh
Name: State, dtype: object

In [60]:
#locate by row index ==  row label
cities.iloc[2] == cities.loc['Allahabad']
#st_indx:last_indx == st_label:end_label
cities.iloc[2:4] == cities.loc['Allahabad':'Amritsar']
#Column , particular index label
cities['Population_2011'].loc[['Allahabad']]
#specific rowindx,colindx
cities.iloc[1:3, 2]
#rowvalue,columnname
cities.loc['Allahabad','State'] == cities.at['Allahabad','State']
#all the values after a sp row.
cities.loc['Vadodara':,'State'] == cities.loc['Vadodara':]['State']

City
Vadodara         True
Varanasi         True
Vasai-Virar      True
Vijayawada       True
Visakhapatnam    True
Name: State, dtype: bool

In [43]:
cities['Population_2011']

City
Agra                 1574542
Ahmedabad            5570585
Allahabad            1117094
Amritsar             1132761
Anantnag             1078692
Aurangabad           1171330
Bangalore            8425970
Bhopal               1795648
Chandigarh            960787
Chennai              4681087
Coimbatore           1061447
Delhi               11007835
Dhanbad              1161561
Faridabad            1404653
Ghaziabad            1636068
Guwahati              963429
Gwalior              1053505
Howrah               1072161
Hyderabad            7170545
Indore               1960631
Jabalpur             1054336
Jaipur               3073350
Jodhpur              1033918
Kalyan-Dombivali     1246381
Kanpur               2767031
Kolkata              4486679
Kota                 1001365
Lucknow              2815601
Ludhiana             1613878
Madurai              1016885
Meerut               1309023
Mumbai              12478447
Nagpur               2405421
Nashik               1486973
Navi Mumbai          1119477
Patna                1683200
Pimpri-Chinchwad     1729359
Pune                 3115431
Raipur               1010087
Rajkot               1286995
Ranchi               1073440
Solapur               951118
Srinagar             1192792
Surat                4462002
Thane                1818872
Vadodara             1666703
Varanasi             1201815
Vasai-Virar          1221233
Vijayawada           1034358
Visakhapatnam        1897823
Name: Population_2011, dtype: int64